version: "3.3"

services:
  backend:
    image: car_selling:1.0
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - 5000:5000
    command: nodemon index

  mysql:
    image: mysql/mysql-server
    restart: always
    ports:
      - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_USERNAME=root
      - MYSQL_ROOT_PASSWORD=123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 82:80
    volumes:
      - /etc/phpmyadmin/config.user.inc.php
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
